### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/subscriptions-transport-ws#5]
I setup AppVeyor for this project, all you'll need to do is add an `appveyor.yml`.

https://ci.appveyor.com/project/graphql-dotnet-ci/subscriptions-transport-ws

**Comment by pekkah** [comment]
@joemcbride thanks :) I was going to ask you about it tomorrow.

**Comment by pekkah** [comment]
Basic build done using Cake. @joemcbride couldn't get the build badge to work. Displaying build status unknown..

**Comment by joemcbride** [comment]
Looks like AppVeyor has switched to a different format now for whatever reason.

```markdown
[![Build status](https://ci.appveyor.com/api/projects/status/11e1i3yp07jy18jj/branch/master?svg=true)](https://ci.appveyor.com/project/graphql-dotnet-ci/subscriptions-transport-ws/branch/master)
```

[![Build status](https://ci.appveyor.com/api/projects/status/11e1i3yp07jy18jj/branch/master?svg=true)](https://ci.appveyor.com/project/graphql-dotnet-ci/subscriptions-transport-ws/branch/master)
